version: "3.2"

services:
  library_backend:
    container_name: library_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    links:
      - mongo
    networks:
      - webappnetwork
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    command: mongod --bind_ip_all
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
